### ISSUE TITLE
Wrong position of input text

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/Raphael.InlineTextEditing#2]
Text inputs are wrongly placed: they are positioned relatively to the window, and not to the SVG container.

For instance, change container style to the following in the demonstration:

``` css
#canvas_container {
  width: 740px;
  height: 540px;
  border: 1px solid #aaa;
  margin-top: 400px;
  margin-left: 300px;
}
```

And try to edit a text. The input exits the container.
